version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.7
    steps:
      - checkout
      - run:
          name: 'Bundle install'
          command: 'bundle install'
      - run:
          name: 'Set up database'
          command: 'bin/rails db:schema:load'
